### ISSUE TITLE
Add option to specify sandbox or production API

### ISSUE THREAD

**Issue by mos-ie** [eBay/FeedSDK#1]
Currently all request go to the production API.  It would be nice if we could explicitly say what API environment we want to call e.g.

`FeedRequest.FeedRequestBuilder builder = new FeedRequestBuilder();      
builder.categoryId(CATEGORY).date(DATE).feedScope(SCOPE).siteId(MKT).token(token).type(FeedTypeEnum.ITEM).environment(EnvTypeEnum.SANDBOX);`

**Comment by shankar-ganesh-ebay** [comment]
@mos-ie That's a good suggestion. 
Would you like to contribute this feature back into the SDK as PR ? If not, I'll add this feature in the next release shortly.

**Comment by mos-ie** [comment]
@shankar-ganesh-ebay thanks! I'll see if I can find some time. If not, how long would it be until the next release?

**Comment by shankar-ganesh-ebay** [comment]
@mos-ie We are planning a release by end of this week with a bug fix. The feature you have requested would be part of that release. I'll keep you posted.

**Comment by skumaravelayutham** [comment]
Fixed in this commit: f093b8f & #3

**Comment by mos-ie** [comment]
@shankar-ganesh-ebay @skumaravelayutham brilliant, thanks guys!
